version: '3'
services:

  slackconcierge:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/github.com/disiqueira/slackconcierge
    environment:
      SLACK_TOKEN: "xoxb-192960921860-J6wCZIeD5sl7H91Odp4gi4dE"
      GO111MODULE: "on"
