version: '3'
services:

  slackconcierge:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/github.com/disiqueira/slackconcierge
    env_file:
      - .env
      GO111MODULE: "on"
